# Generated by Django 5.2 on 2025-06-10 16:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('interprete', models.CharField(max_length=200)),
                ('compositor', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('derechos_autor', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReproduccionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('duracion_escuchada', models.DurationField(blank=True, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones', to='audios.audio')),
            ],
            options={
                'db_table': 'audio_reproducciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
