# Generated by Django 5.2 on 2025-05-26 17:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('interprete', models.CharField(max_length=200)),
                ('compositor', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('derechos_autor', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
    ]
