# Generated by Django 5.2 on 2025-06-21 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_alter_audio_options_audio_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('audio_descargado', models.CharField(max_length=200)),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audios.audio')),
            ],
            options={
                'verbose_name': 'Contacto de Descarga',
                'verbose_name_plural': 'Contactos de Descarga',
                'ordering': ['-fecha_descarga'],
            },
        ),
    ]
