# Generated by Django 5.2 on 2025-06-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0004_contactodescarga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reproduccionaudio',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Reproducción', 'verbose_name_plural': 'Reproducciones'},
        ),
        migrations.RemoveField(
            model_name='contactodescarga',
            name='audio_descargado',
        ),
    ]
