# Generated by Django 5.2 on 2025-06-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0005_alter_reproduccionaudio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactodescarga',
            options={'ordering': ['-fecha_descarga'], 'verbose_name': 'Registro de Descarga', 'verbose_name_plural': 'Registros de Descargas'},
        ),
        migrations.AlterField(
            model_name='contactodescarga',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audios.audio', verbose_name='Audio Descargado'),
        ),
    ]
